Resources:
  bcadmin:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: quarterId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: quarterId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  bcadminSlug:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bcadmin-slug
      AttributeDefinitions:
        - AttributeName: slug
          AttributeType: S
        - AttributeName: title
          AttributeType: S
      KeySchema:
        - AttributeName: slug
          KeyType: HASH
        - AttributeName: title
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  bcadminClasses:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bcadmin-classes
      AttributeDefinitions:
        - AttributeName: slug
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: slug
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST